# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#top-level-configuration
tutorial: false

logging:
  level: INFO
  format: '%(levelname)s:%(name)s:%(message)s'

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  name: "247myopic"
  disable_progressbar: false
  shared_resources: false
  shared_cutouts: true

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#foresight
foresight: myopic

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#scenario
# Wildcard docs in https://pypsa-eur.readthedocs.io/en/latest/wildcards.html
scenario:
  weather_year: [''] # for backwards compatibility
  simpl:
  - ''
  ll:
  - v1.0
  clusters:
  - 37
  opts:
  - ''
  sector_opts:
  - Co2L0-3H-B-solar+p3
  planning_horizons:
  - 2025
  #- 2030

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#countries
countries: ['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK']

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#snapshots
snapshots:
  start: "2013-01-01"
  end: "2014-01-01"
  inclusive: 'left'

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#enable
enable:
  retrieve: auto
  prepare_links_p_nom: false
  retrieve_databundle: true
  retrieve_sector_databundle: true
  retrieve_cost_data: true
  build_cutout: false
  retrieve_cutout: true
  retrieve_opsd_load_data: true
  retrieve_artificial_load_data: false
  build_natura_raster: false
  retrieve_natura_raster: true
  custom_busmap: false
  drop_leap_days: true
